"""empty message

Revision ID: 5e34f24ae79f
Revises: ec105fa14dad
Create Date: 2021-11-23 17:28:50.708119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86bcbc87d87'
down_revision = 'ec105fa14dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_blacklisted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_blacklisted'], ['User.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Blacklist')
    # ### end Alembic commands ###
